---
jobs:
  create-instance:
    name: Try to create OCI ARM instance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Validate composer.json
        run: composer validate
      - id: composer-cache
        name: Get Composer Cache Directory
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          path: ${{ steps.composer-cache.outputs.dir }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress
      - env:
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_MAX_INSTANCES: ${{ secrets.OCI_MAX_INSTANCES }}
          OCI_MEMORY_IN_GBS: ${{ secrets.OCI_MEMORY_IN_GBS }}
          OCI_OCPUS: ${{ secrets.OCI_OCPUS }}
          OCI_PRIVATE_KEY_FILENAME: ${{ secrets.OCI_PRIVATE_KEY_FILENAME }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_SHAPE: ${{ secrets.OCI_SHAPE }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
        name: Run script
        run: php index.php
name: OCI ARM Instance Creator
'on':
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'